// Pharmacy Action Type

export const GET_SUPPLIER_INFO = "GET_SUPPLIER_INFO";
export const GET_SUPPLIER_STATEMENT = "GET_SUPPLIER_STATEMENT";
export const GET_DRUG_LIST = "GET_DRUG_LIST";
export const GET_PURCHASE_ITEM = "GET_PURCHASE_ITEM";
export const GET_PHARM_STORE = "GET_PHARM_STORE";
export const PHARM_LOADING = "PHARM_LOADING";
export const GET_CLIENT_INFO = "GET_CLIENT_INFO";
export const GET_CLIENT_STATEMENT = "GET_CLIENT_STATEMENT";
export const SALES = "SALES";
export const PHARM_USER = "PHARM_USER";
export const RECEIPT_DATA = "RECEIPT_DATA";
export const SUPPLIER_COUNT='SUPPLIER_COUNT';
export const GET_STOCK_INFO="GET_STOCK_INFO";
export const GET_STOCK_INFO_STORE='GET_STOCK_INFO_STORE';
export const GET_STOCK_INFO_STORE_SHELF='GET_STOCK_INFO_STORE_SHELF';
export const GET_TOP_SALES='GET_TOP_SALES';
export const GET_REORDER_LEVEL='GET_REORDER_LEVEL';
export const GET_EXPIRY_ALERT='GET_EXPIRY_ALERT';
export const GET_TOTAL_DRUG='GET_TOTAL_DRUG';
export const REPORT_LIST = "REPORT_LIST";
export const DISPATCH_AMOUNT_PAID="DISPATCH_AMOUNT_PAID";
export const DISPATCH_DISCOUNT="DISPATCH_DISCOUNT"

// user Action Type 

export const LOADING='LOADING'
export const LOGIN='LOGIN'
export const ERROR="ERROR"
export const LOGOUT= "LOGOUT"
export const CREATING_USER="CREATING_USER" 
export const ERROR_CREATING_USER='ERROR_CREATING_USER'
export const LOGGING_IN = 'LOGGING_IN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SET_PROFILE = 'SET_PROFILE'
export const RESTORE_TOKEN = 'RESTORE_TOKEN'
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING'
export const SET_APP_THEME = 'SET_APP_THEME'
export const SET_ACTIVE_BUSINESS = 'SET_ACTIVE_BUSINESS'
export const SET_FORM_SETUP = 'SET_FORM_SETUP'